import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs'
import Header from "@/components/Header";
import Sidebar from "@/components/Sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" data-theme="night">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Header/>


        <div className="flex min-h-screen">

          {/* sidebar */}

          <Sidebar/>

          <div className="flex-1 p-4 bg-gray-900 overflow-y-auto scrollbar-hide">
          {children}
          </div>
      
        </div>



          
        </body>
      </html>
    </ClerkProvider>
  );
}
